In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
num_episodes = 20000
max_steps_per_episode = 100

learning_rate = 0.08
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []

In [7]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): 


        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            #exploit the environment
            action = np.argmax(q_table[state,:]) 
        else:
            #explore the enviroment
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        # Update Q-table for Q(s,a)
        q_table[state, action] =q_table[state, action] + learning_rate * ((reward + discount_rate * np.max(q_table[new_state, :])) - q_table[state, action])
        
        state = new_state
        rewards_current_episode += reward 
        
        if done == True:                                                                                 
            break
                                                                                                 
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)   


![title](Capture.PNG)

In [33]:
exploration_rate

0.01000000204258365

In [8]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.026000000000000016
2000 :  0.19100000000000014
3000 :  0.4010000000000003
4000 :  0.5490000000000004
5000 :  0.6300000000000004
6000 :  0.6220000000000004
7000 :  0.6810000000000005
8000 :  0.7060000000000005
9000 :  0.6550000000000005
10000 :  0.6650000000000005
11000 :  0.6930000000000005
12000 :  0.6630000000000005
13000 :  0.7190000000000005
14000 :  0.6920000000000005
15000 :  0.7210000000000005
16000 :  0.6920000000000005
17000 :  0.6790000000000005
18000 :  0.6970000000000005
19000 :  0.6920000000000005
20000 :  0.6790000000000005


In [9]:
for episode in range(3):
    state = env.reset()
    done = False
    
    
    for step in range(max_steps_per_episode): 
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:]) 
       
        new_state, reward, done, info = env.step(action)
        # Update Q-table for Q(s,a)   
        state = new_state
    
        if done == True:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)                                                                                     
            break
                                                                                  
env.close() 

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****


In [ ]:
exploration_rate

In [10]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.51652152 0.47969242 0.47990939 0.48822852]
 [0.38341883 0.28933983 0.3740858  0.46668443]
 [0.397259   0.42646114 0.40850691 0.43522256]
 [0.20500289 0.25826667 0.29999498 0.41879554]
 [0.54116529 0.31196496 0.4233821  0.37663585]
 [0.         0.         0.         0.        ]
 [0.30913862 0.19087917 0.16731368 0.13310463]
 [0.         0.         0.         0.        ]
 [0.28717076 0.49720563 0.36958263 0.57752907]
 [0.56301801 0.59626223 0.37487015 0.47643448]
 [0.52467036 0.40124773 0.44166569 0.33714119]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.51933134 0.61879386 0.70840395 0.58724869]
 [0.68381367 0.87404224 0.77831225 0.77067037]
 [0.         0.         0.         0.        ]]
